import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import Header from "@/components/Header";
import "./globals.css";
import Footer from "@/components/Footer";

const montserrat = Montserrat({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Guna Ulang",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" style={{height: '100%'}}>
      <body className={montserrat.className} style={{height: '100%' , position: "relative" }}>
        <Header />
        <div style={{ minHeight: "100%" }}>{children}</div>
        <Footer />
      </body>
    </html>
  );
}
